# Generated by Django 5.2.5 on 2025-08-30 10:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('author', models.CharField(default='User', max_length=200)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('link', models.URLField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('answer_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile_image', models.ImageField(default='default.img', upload_to='')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='content_que_created_453641_idx'), models.Index(fields=['-score'], name='content_que_score_b2591d_idx'), models.Index(fields=['-last_activity_date'], name='content_que_last_ac_411fdd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.IntegerField(unique=True)),
                ('body', models.TextField(blank=True)),
                ('score', models.IntegerField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('last_activity_date', models.DateTimeField()),
                ('owner_display_name', models.CharField(max_length=100)),
                ('owner_profile_image', models.URLField(default='default.img')),
                ('owner_reputation', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='content.question')),
            ],
            options={
                'ordering': ['-score', '-is_accepted'],
            },
        ),
    ]
