# Generated by Django 5.2.5 on 2025-08-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
                ('reputation', models.IntegerField(default=0)),
                ('profile_image', models.ImageField(default='default.img', upload_to='')),
                ('account_id', models.IntegerField(default=0)),
            ],
        ),
    ]
