# Generated by Django 5.2.5 on 2025-09-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='profile_link',
            field=models.URLField(default='default.img'),
        ),
    ]
