# Generated by Django 5.2.5 on 2025-09-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_question_profile_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='profile_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
