# Generated by Django 5.2.5 on 2025-09-01 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_question_profile_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='link',
            new_name='question_link',
        ),
    ]
