# Generated by Django 5.2.5 on 2025-09-01 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_rename_link_question_question_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='profile_link',
            field=models.URLField(default='www.google.com'),
        ),
    ]
