# Generated by Django 5.2.5 on 2025-09-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_question_profile_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='profile_link',
            field=models.URLField(default='default.img'),
        ),
        migrations.AlterField(
            model_name='question',
            name='profile_link',
            field=models.URLField(default='default.img'),
        ),
    ]
