# Generated by Django 5.2.5 on 2025-09-01 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_answer_profile_link_alter_question_profile_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='profile_link',
            new_name='owner_profile_link',
        ),
    ]
