# Generated by Django 5.2.5 on 2025-09-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_tag_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='tags',
            field=models.ManyToManyField(related_name='answers', to='content.tag'),
        ),
    ]
