# Generated by Django 5.2.5 on 2025-09-01 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_answer_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='owner_profile_image',
            field=models.URLField(default='https://share.google/images/sZNPcYSLjis7n9HqX'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='owner_profile_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='profile_image',
            field=models.ImageField(default='https://share.google/images/sZNPcYSLjis7n9HqX', upload_to=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='profile_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
