# Generated by Django 5.2.5 on 2025-09-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_answer_owner_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.URLField(blank=True, null=True)),
                ('question_title', models.CharField(max_length=200)),
                ('question_body', models.TextField(blank=True)),
                ('question_remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
