# Generated by Django 5.2.5 on 2025-09-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_user_question_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_question',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
