# Generated by Django 5.2.5 on 2025-09-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_user_question_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.URLField(blank=True, null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('question_id', models.IntegerField(default=0)),
                ('question_link', models.URLField(blank=True, null=True)),
                ('answer_title', models.CharField(max_length=200)),
                ('answer_body', models.TextField(blank=True)),
                ('answer_remarks', models.TextField(blank=True)),
            ],
        ),
    ]
